// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6mqqw7E0wkss378pR2oRdU8wT06GSOQ0',
    appId: '1:734456671677:web:ebd9a1a2902a02acee36d4',
    messagingSenderId: '734456671677',
    projectId: 'the-visionaries-mobile',
    authDomain: 'the-visionaries-mobile.firebaseapp.com',
    storageBucket: 'the-visionaries-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiggezgXgmYVWF4qnWblRcL0cSPQW3IFs',
    appId: '1:734456671677:android:992fc092296ece97ee36d4',
    messagingSenderId: '734456671677',
    projectId: 'the-visionaries-mobile',
    storageBucket: 'the-visionaries-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0senr4OFcXHKwb5au2dsLWHVBJfBCvuE',
    appId: '1:734456671677:ios:1e7efafb6b176e2fee36d4',
    messagingSenderId: '734456671677',
    projectId: 'the-visionaries-mobile',
    storageBucket: 'the-visionaries-mobile.firebasestorage.app',
    iosBundleId: 'com.example.theVisionaries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0senr4OFcXHKwb5au2dsLWHVBJfBCvuE',
    appId: '1:734456671677:ios:1e7efafb6b176e2fee36d4',
    messagingSenderId: '734456671677',
    projectId: 'the-visionaries-mobile',
    storageBucket: 'the-visionaries-mobile.firebasestorage.app',
    iosBundleId: 'com.example.theVisionaries',
  );
}